server:
  port: 5000
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 12000
  ConnectTimeout: 12000
  eureka:
    enabled: true
zuul:
  prefix: /v1
  routes:
    eureka-client: /hiapi/**
    eureka-feign-client: /feignapi/**
    eureka-ribbon-client: /ribbonapi/**
