server:
  port: 8769
spring:
  application:
    name: service-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  combine-host-port: true
  app-config: eureka-feign-client,eureka-ribbon-client
  cluster-name-expression: new String("default")
  aggregator:
    cluster-config: default
  instanceUrlSuffix: /hystrix.stream
